# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('year', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('markdown', models.TextField(default=b'# HST Policy Agreement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
