# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-08 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(editable=False)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nPages', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
