# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radmin', '0003_auto_20180508_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='id',
        ),
        migrations.AlterField(
            model_name='policy',
            name='markdown',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False),
        ),
    ]
