# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-09 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radmin', '0004_auto_20180508_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='nPages',
        ),
        migrations.AlterField(
            model_name='policy',
            name='markdown',
            field=models.TextField(default=b'# HST Policy Agreement'),
        ),
    ]
