# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='owner_type',
            field=django_mysql.models.EnumField(choices=[(b'Family', b'Family'), (b'Student', b'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], null=True),
        ),
    ]
