# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-10 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='father_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
