# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-09 21:55
from __future__ import unicode_literals

import apps.main.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alt_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='alt_phone',
            field=apps.main.custom_fields.PhoneNumberField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='alt_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='alt_phone',
            field=apps.main.custom_fields.PhoneNumberField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prefer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
