# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-09 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171209_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='father_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='mother_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
