# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-06 21:27
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171206_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner_type',
            field=django_mysql.models.EnumField(choices=[(b'Family', b'Family'), (b'Student', b'Student')], null=True),
        ),
    ]
