# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-08 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171207_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
