# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-05 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_family_joined_hst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floop', models.CommaSeparatedIntegerField(max_length=6)),
            ],
        ),
    ]
