# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_est_grad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='est_grad',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
