# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-10 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171209_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='father_id',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother_id',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='family',
        ),
        migrations.AddField(
            model_name='family',
            name='father',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='main.PARENT'),
        ),
        migrations.AddField(
            model_name='family',
            name='mother',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='main.PARENT'),
        ),
    ]
