# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-15 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171214_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tshirt',
            field=models.CharField(choices=[('YS', 'Youth Small'), ('YM', 'Youth Medium'), ('YL', 'Youth Large'), ('XS', 'Adult Extra Small'), ('AS', 'Adult Small'), ('AM', 'Adult Medium'), ('AL', 'Adult Large'), ('XL', 'Adult Extra Large'), ('2X', 'Adult 2XL'), ('3X', 'Adult 3XL')], max_length=2, null=True),
        ),
    ]
