# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-10 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171209_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='mother',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='main.PARENT'),
        ),
    ]
