# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-15 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171214_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='est_grad',
            new_name='grad_year',
        ),
    ]
