# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_family_reg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='reg_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
