# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_csi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
