# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171205_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
