# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171214_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
