# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 18:15
from __future__ import unicode_literals

import apps.main.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current',
            field=apps.main.custom_fields.BooleanField(),
        ),
    ]
